FROM node:16

WORKDIR /usr/src/app

COPY ["package.json", "./package.json"]
COPY ["tsconfig.json", "./tsconfig.json"]

RUN npm install
RUN npm install typescript
RUN npm run build

CMD ["npm", "start"]

EXPOSE 3005