name: Deploy backend-api
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      - name: build image
        run: cd server && docker build . -t aneeshseth/dummy-api:${{ github.sha }}
      
      - name: push image
        run: docker push aneeshseth/dummy-api:${{ github.sha }}
      
      - name: creating a zip file
        run: cd server && mkdir deploy && 